# Generated by Django 5.0.9 on 2025-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('path', models.CharField(max_length=255, verbose_name='文件夹路径')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
            ],
            options={
                'verbose_name': '本地文件',
                'verbose_name_plural': '本地文件',
            },
        ),
    ]
