# Generated by Django 5.0.9 on 2025-02-12 06:32

import backend.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_localfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfile',
            name='app',
            field=models.CharField(default='common', max_length=255, verbose_name='隶属APP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localfile',
            name='file',
            field=models.FileField(upload_to=backend.project.models.file_upload_to, verbose_name='文件'),
        ),
    ]
