# Generated by Django 5.0.9 on 2024-12-16 18:48

import backend.datasource.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=255, verbose_name='数据集名称')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.datasource.models.datasource_image_upload_to, verbose_name='封面图')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路径')),
                ('team_id', models.IntegerField(blank=True, null=True, verbose_name='团队 ID')),
                ('belong', models.CharField(default='private', max_length=255, verbose_name='归属性质')),
                ('files', models.JSONField(default=list, verbose_name='文件列表')),
                ('read_me', models.TextField(default='', verbose_name='详细描述')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
            },
        ),
        migrations.CreateModel(
            name='DatasourceFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_id', models.IntegerField(verbose_name='数据集ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '数据集收藏',
                'verbose_name_plural': '数据集收藏',
            },
        ),
    ]
