# Generated by Django 5.0.9 on 2024-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='组件名称')),
                ('source', models.TextField(verbose_name='源代码')),
                ('paramsConfig', models.JSONField(default=dict, verbose_name='参数配置')),
                ('inputConfig', models.JSONField(default=dict, verbose_name='输入参数')),
                ('outputConfig', models.JSONField(default=dict, verbose_name='输出参数')),
                ('team_id', models.IntegerField(blank=True, null=True, verbose_name='所属团队')),
                ('category', models.CharField(max_length=50, verbose_name='所属分组')),
                ('genre', models.CharField(default='common', max_length=50, verbose_name='组件类型')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '分析组件',
                'verbose_name_plural': '分析组件',
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=50, verbose_name='分组名称')),
                ('genre', models.CharField(default='common', max_length=50, verbose_name='分组类型')),
                ('key', models.CharField(max_length=255, verbose_name='分类Key')),
            ],
            options={
                'verbose_name': '组件分类',
                'verbose_name_plural': '组件分类',
            },
        ),
        migrations.CreateModel(
            name='ComponentFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.IntegerField(verbose_name='组件ID')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '组件收藏',
                'verbose_name_plural': '组件收藏',
            },
        ),
    ]
